" .vimrc by Alexander Olzem

set nocompatible

"+---------------------------------------------------------------------------+
"| Settings                                                                  |
"+---------------------------------------------------------------------------+

" Colors
set bg=dark
autocmd colorscheme * hi clear SpellBad
autocmd colorscheme * hi SpellBad cterm=underline ctermfg=NONE ctermbg=NONE
highlight LineNr ctermfg=grey
highlight ColorColumn ctermbg=darkgrey
highlight Pmenu ctermbg=darkgrey ctermfg=white
highlight PmenuSel ctermbg=blue ctermfg=black

" Enable auto indenting
if has('filetype')
  filetype indent plugin on
endif

" Enable syntax highliting
if has('syntax')
  syntax on
endif

" spellcheck
augroup spellchecking
  au!
  autocmd FileType markdown setlocal spell
  autocmd BufRead,BufNewFile *.md setlocal spell
  autocmd BufRead,BufNewFile *.MD setlocal spell
  autocmd FileType gitcommit setlocal spell
augroup END

" When editing a file, always jump to the last known cursor position.
augroup vimStartup
  autocmd BufReadPost *
      \ if line("'\"") >= 1 && line("'\"") <= line("$") && &ft !~# 'commit'
      \ |   exe "normal! g`\""
      \ | endif


" Highlight trailing whitespace
highlight TrailingWhitespace ctermbg=darkgrey guibg=darkgrey
call matchadd("TrailingWhitespace", '\v\s+$')
set listchars=tab:>>,trail:.
set list

set undolevels=1000
set undoreload=10000

" Keep buffers in background
set hidden

" Save .viminfo in .vim to keep home clean
set viminfo+=n$HOME/.vim/viminfo

" Better command-line completion
set wildmenu

" Show partial commands in the last line of the screen
set showcmd

" Stop certain movements from always going to the first character of a line.
set nostartofline

" Display the cursor position on the last line of the screen or in the status line of a window
set ruler

" Always display the status line, even if only one window is displayed
set laststatus=2

" Instead of failing a command because of unsaved changes, raise a dialogue asking if you wish to save changed files.
set confirm

" Disable mouse and bell
set visualbell t_vb=
set mouse=
if !has('nvim')
  set ttymouse=
endif

" Set the command window height to 2 lines
set cmdheight=2

" Display line numbers on the left
set number

" Use <F11> to toggle between 'paste' and 'nopaste'
set pastetoggle=<F11>

" Set ruler at the right
set colorcolumn=120

" Completion options
set completeopt+=menuone
set completeopt+=noselect
set previewheight=5

" Shut off completion messages
set shortmess+=c

" Indentation
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2
augroup tabs
  autocmd FileType Makefile set noexpandtab
  autocmd BufNewFile,BufRead *.go set noexpandtab tabstop=4 shiftwidth=4
augroup END

" Search options
set nohlsearch
set incsearch
set ignorecase
set smartcase
set scrolloff=4
set path+=**

"+---------------------------------------------------------------------------+
"| Remaps                                                                    |
"+---------------------------------------------------------------------------+

let mapleader=" "

nnoremap Y y$

" Center next / previous
nnoremap n nzzzv
nnoremap N Nzzzv

" Keep the cursor where it was after line concatination
nnoremap J mzJ`z

" Undo break points at end of sentences
inoremap , ,<c-g>u
inoremap . .<c-g>u
inoremap : :<c-g>u
inoremap ; ;<c-g>u
inoremap - -<c-g>u
inoremap ! !<c-g>u
inoremap ? ?<c-g>u

" Moving Text
vnoremap J :m '>+1<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv

nnoremap <leader>k :m .-2<CR>==
nnoremap <leader>j :m .+1<CR>==

nnoremap <leader>N :set number<CR>
nnoremap <leader>n :set nonumber<CR>

nnoremap <leader>f gqip

au FileType go nmap <leader>r :!go run %<CR>
au FileType go nmap <leader>t :!go test<CR>

au FileType sh nmap <leader>r :!./%<CR>
au FileType sh nmap <leader>t :!shellcheck %<CR>

au FileType terraform nmap <leader>r :!terraform apply<CR>
au FileType terraform nmap <leader>t :!terraform validate<CR>

au FileType c nmap <leader>r :!gcc -o /tmp/%.o % && /tmp/%.o<CR>

au FileType python nmap <leader>r :!python3 %<CR>
