#!/bin/sh

secret=""

while IFS= read -r line; do
  secret="$secret$line\n"
done

for i in $(echo "$secret" | yq -r '.data | keys | join " "'); do
  decoded=$(echo "$secret" | yq -r ".data[\"$i\"]" | base64 -d)
  secret=$(echo "$secret" | yq -r ".stringData[\"$i\"] = \"$decoded\"")
done
secret=$(echo "$secret" | yq -r "del(.data)")

echo "$secret" | yq
