#!/bin/bash

url="ix.io"

if [[ -t 0 ]]; then
  # Get file from arg
  if [[ -f "$1" ]]; then
    curl -F f:1=@"$1" "$url"
  else
    curl "$url/$1"
  fi
else
  # Read from stdin
  curl -F f:1="<-" "$url"
fi

