#!/bin/bash
# shellcheck disable=SC2139

# Get rid of default aliases
unalias -a

# Grepping
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'

# Git
alias gc='git commit'
alias gd='git diff'
alias gs='git status'
alias gp='git push'
alias gl='git log --oneline'
alias gu='git remote update'
alias gap='git add -p'

# Kubernetes
alias kgc='kubectl config get-contexts'
alias kuc='kubectl config use-context'

# ls
alias ls='ls --color=auto --group-directories-first'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -laH'

# confirmation
alias mv='mv -i'
alias rm='rm -I --preserve-root'

# Other
alias tf='terraform'
alias chmox='chmod +x'
alias ports='netstat -atulpn'
alias S='sudo systemctl'
alias watch='watch -n 1'
alias d='docker'

vimcmd=vim
if [ -n "$(command -v nvim)" ]; then vimcmd=nvim; fi
alias v="$vimcmd"
alias vi="$vimcmd"
alias vim="$vimcmd"
alias cim="$vimcmd"

if [ -n "$(command -v zoxide)" ]; then
  eval "$(zoxide init bash)"
  alias cd="z"
fi

for i in $(seq 2 4); do
  alias "$(for _ in $(seq "$i"); do printf "."; done)=cd $(for _ in $(seq "$((i-1))"); do printf "../"; done)"
done
