#!/bin/sh

count=0
while read -r line; do
  [ -t 0 ] && printf '\033[1A\033[2K'
  if [ ! "$line" = "q" ]; then
    count=$((count + 1))
    [ "$1" = "-v" ] && printf '%d\n' "$count"
  else
    printf 'Result: %d\n' "$count"
    exit 0
  fi
done

