#!/bin/sh

installdir="$HOME/.local/bin"

curl -sLo "/tmp/shellcheck-stable.tar.xz" "https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz"
tar -xf /tmp/shellcheck-stable.tar.xz
cp "shellcheck-stable/shellcheck" "$installdir/shellcheck"
rm -r "shellcheck-stable"
rm "/tmp/shellcheck-stable.tar.xz"

