#!/bin/sh

installdir="/usr/local"
version="1.17.8"

wget "https://go.dev/dl/go$version.linux-amd64.tar.gz"
tar -xzf "./go$version.linux-amd64.tar.gz" && \
    rm "./go$version.linux-amd64.tar.gz"
sudo mv ./go "$installdir/go"

