#!/bin/sh

installdir="$HOME/.local/bin"

curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
install minikube-linux-amd64 "$installdir/minikube" && rm minikube-linux-amd64

