#!/bin/bash

server="gitlab.com"

ssh-keygen -t rsa -b 2048 -P "" -C "GitLab - $HOSTNAME" -f "$HOME/.ssh/${server//./_}_rsa"
cat >> "$HOME/.ssh/config" << EOF
Host $server
  PreferredAuthentications publickey
  IdentityFile $HOME/.ssh/${server//./_}_rsa
EOF
chmod 700 "$HOME/.ssh"
chmod 400 "$HOME/.ssh/config"
chmod 600 "$HOME/.ssh/gitlab_com_rsa"
chmod 644 "$HOME/.ssh/gitlab_com_rsa.pub"

printf 'Add the following key to your GitLab Profile:\n\n'
cat "$HOME/.ssh/gitlab_com_rsa.pub"
printf '\n\n'

