#!/bin/bash

server="${1:-github.com}"

ssh-keygen \
  -t rsa \
  -b 4096 \
  -P "" \
  -C "${HOSTNAME:-$USER}" \
  -f "$HOME/.ssh/${server//./_}_rsa"

cat >> "$HOME/.ssh/config" << EOF
Host $server
  PreferredAuthentications publickey
  IdentityFile ~/.ssh/${server//./_}_rsa
EOF

chmod 700 "$HOME/.ssh"
chmod 600 "$HOME/.ssh/config"
chmod 600 "$HOME/.ssh/${server//./_}_rsa"
chmod 644 "$HOME/.ssh/${server//./_}_rsa.pub"

printf 'Add the following key to your %s Profile:\n\n' "$server"
cat "$HOME/.ssh/${server//./_}_rsa.pub"
printf '\n\n'

