#!/bin/bash

# Dependencies
# - curl
# - extract script

# Setup install directory
installdir="$HOME/.local/bin"
[ ! -d "$installdir" ] && mkdir -p "$installdir"

###############################################################################
# Functions                                                                   #
###############################################################################

info() {
  printf '\nINSTALLING: %s\n' "$1"
  printf '%*s\n' '80' | tr ' ' '-'
}

# install a github release
#   $1 = link to the github release download
#   $2 = name of the binary file inside the archive
#   $3 = optional string to rename the file in install directory
install_github_release() {
  release_link="$1"
  release_tar="${release_link##*/}"
  release_bin="$2"
  rename_name="$3"
  if [[ -z "$rename_name" ]]; then rename_name="$release_bin"; fi
  info "$release_bin"
  curl -Lo "$release_tar" "$release_link" || exit 1
  files="$(extract "$release_tar")" && rm "$release_tar"
  for file in $files; do
    if [[ ${file##*/} == $release_bin ]]; then
      release_path=$file
    fi
  done
  install "$release_path" "$installdir/$rename_name"
  rm -rf "${release_path%%/*}"
}

# install a file from a download link
#   $1 = download link
#   $2 = optional string to rename the file in install directory
install_from_download_link() {
  download_link="$1"
  rename_name="$2"
  downloaded_file="${download_link##*/}"
  if [[ -z "$rename_name" ]]; then rename_name="$downloaded_file"; fi
  info "$rename_name"
  curl -Lo "$downloaded_file" "$download_link"
  install "$downloaded_file" "$installdir/$rename_name"
  rm "$downloaded_file"
}

###############################################################################
# Binaries get installed here                                                 #
###############################################################################

# gh
install_github_release 'https://github.com/cli/cli/releases/download/v2.27.0/gh_2.27.0_linux_amd64.tar.gz' 'gh'

# shellcheck
install_github_release 'https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz' 'shellcheck'

# logcli
install_github_release 'https://github.com/grafana/loki/releases/download/v2.8.0/logcli-linux-amd64.zip' 'logcli-linux-amd64' 'logcli'

# jq
install_from_download_link 'https://stedolan.github.io/jq/download/linux64/jq'

# kubectl
version="$(curl -L -s https://dl.k8s.io/release/stable.txt)"
install_from_download_link "https://dl.k8s.io/release/$version/bin/linux/amd64/kubectl"

# minikube
install_from_download_link 'https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64' 'minikube'

# yq
version="$(curl -s https://github.com/mikefarah/yq/releases/latest | grep -oP 'v[\d\.]+')"
install_from_download_link "https://github.com/mikefarah/yq/releases/download/$version/yq_linux_amd64" 'yq'
