## Git Status Information
# Icon	Description
# =	This branch has merge conflicts.
# ⇡	ahead
# ⇣	behind
# ⇕	diverged
# ?	untracked
# $	stashed
# !	modified
# +	staged
# »	renamed
# ✘	deleted

format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$python\
$rust\
$time\
$status\
$shell\
$character"""

[line_break]
disabled = true

[username]
style_user  = "white bold"
style_root  = "red bold"
format      = "[$user]($style) "
disabled    = false
show_always = true

[shell]
bash_indicator = "\nbash"
zsh_indicator = "\nzsh"
unknown_indicator = "mystery shell"
disabled = false

[character]
success_symbol = "[❯](bold green) "
error_symbol   = "[✗](bold red) "
vicmd_symbol   = "[V](bold white) "
