format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$python\
$rust\
$time\
$status\
$shell\
$character"""

[line_break]
disabled = true

[username]
style_user  = "white bold"
style_root  = "red bold"
format      = "[$user]($style) "
disabled    = false
show_always = true

# Explicitly show vim mode
[character]
success_symbol = "[insert ❯](bold green) "
error_symbol   = "[insert ✗](bold red) "
vicmd_symbol   = "[❯](bold green) "

