#!/bin/bash
BREAK=4

[ -n "${1}" ] && printf '\x1b[38;5;%smcolour%s\n' "${1}" "${1}" && exit 0

for i in {0..255} ; do
  printf '\x1b[38;5;%smcolour%s \t' "${i}" "${i}"
  if [ $(( i % BREAK )) -eq $((BREAK-1)) ] ; then
    printf "\n"
  fi
done

