#!/bin/bash
FILE="${1:-}"
[[ ! -e "${FILE}" ]] && {
  echo "kubesec: ${FILE}: No such file" >&2;
  exit 1
}

curl --silent \
  --compressed \
  --connect-timeout 5 \
  -sSX POST \
  --data-binary=@"${FILE}" \
  https://v2.kubesec.io/scan

