#!/bin/bash

case $1 in
  apache)
    curl 'https://www.apache.org/licenses/LICENSE-2.0.txt' > "$PWD/LICENSE" ;;
  gpl2)
    curl 'https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt' > "$PWD/LICENSE" ;;
  gpl3)
    curl 'https://www.gnu.org/licenses/gpl-3.0.txt' > "$PWD/LICENSE" ;;
esac
