#!/bin/sh

# Print available snippets
if [ -z "$1" ]; then awk '/^#@ /{print $0}' "$0" | sed 's/^#@ //g' && exit; fi

# Print snippet based on $1
awk "/^#@ $1/{p=1;next} /^$/{p=0} p==1{print \$0}" "$0" | sed 's/^# //g'

#@ k8s-pod
# apiVersion: v1
# kind: Pod
# metadata:
#   name: nginx
# spec:
#   containers:
#   - name: nginx
#     image: nginx:1.14.2
#     ports:
#     - containerPort: 80

#@ k8s-deploy
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-deployment
#   labels:
#     app: nginx
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: nginx
#   template:
#     metadata:
#       labels:
#         app: nginx
#     spec:
#       containers:
#       - name: nginx
#         image: nginx:1.14.2
#         ports:
#         - containerPort: 80

#@ k8s-svc
# apiVersion: v1
# kind: Service
# metadata:
#   name: my-service
# spec:
#   selector:
#     app.kubernetes.io/name: MyApp
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 9376


#@ k8s-ingress
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: minimal-ingress
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   ingressClassName: nginx-example
#   rules:
#   - http:
#       paths:
#       - path: /testpath
#         pathType: Prefix
#         backend:
#           service:
#             name: test
#             port:
#               number: 80
