#!/bin/sh

tmpdir="/tmp/watcher"

[ ! -f "$1" ] || [ $# != 1 ] && exit 1
[ ! -d "$tmpdir" ] && mkdir -p "$tmpdir"

pandoc -o "$tmpdir/content.html" -f markdown_mmd -t html "$1"

csspath="$(which watcher)-ghmd.min.css"
[ ! -f "$tmpdir/style.css" ] && cp $csspath "$tmpdir/style.css"

printf '
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="style.css">
</head>
<article class="markdown-body">' > "$tmpdir/index.html"
cat "$tmpdir/content.html" >> "$tmpdir/index.html"
printf '</article>' >> $tmpdir/index.html

cd "$tmpdir" || exit 1
echo "http://$(hostname):8000"
python3 -m http.server > /dev/null

[ -f "$tmpdir/index.html" ] && rm -v "$tmpdir/index.html"
[ -f "$tmpdir/content.html" ] && rm -v "$tmpdir/content.html"

