#!/bin/sh
[ ! -f "$1" ] || [ $# != 1 ] && exit 1
[ ! -d /tmp/watcher ] && mkdir -p /tmp/watcher

pandoc -o "/tmp/watcher/index.html" -f markdown_mmd -t html "$1"

cd /tmp/watcher || exit 1
echo "http://$(hostname):8000"
python3 -m http.server > /dev/null

[ -f "/tmp/watcher/index.html" ] && rm -v "/tmp/watcher/index.html"

